name: movies
description: A flutter movies app to demonstrate DDD with Riverpod.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  cloud_firestore: ^4.5.0
  google_sign_in: ^6.0.2
  flutter_riverpod: ^2.2.0
  fpdart: ^0.5.0
  sizer: ^2.0.15
  equatable: ^2.0.5
  uuid: ^3.0.7
  dio: ^5.1.0
  go_router: ^6.5.3
  intl: ^0.17.0
  video_player: ^2.6.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
  


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
    

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700